declare const COUNTRY_API_URL: string;
declare const COVID_API_URL: string;

const _COUNTRY_API_URL = COUNTRY_API_URL;
const _COVID_API_URL = COVID_API_URL;

export { _COUNTRY_API_URL as COUNTRY_API_URL, _COVID_API_URL as COVID_API_URL };
